### ISSUE TITLE
[Feature] is there any plans on adding this functionality for Jellyfin?

### ISSUE THREAD

**Issue by elvis0288** [nandyalu/trailarr#10]

**Comment by nandyalu** [comment]
It should already work with Jellyfin. Go into Settings > Trailer and set both `Trailer Folder Movie` and `Trailer Folder Series` to `False`.

**Comment by nandyalu** [comment]
You have to enable `Trailer Monitoring` to see those settings!

**Comment by elvis0288** [comment]
well you do not even need to disable the trailer folder movie.. Jellyfin will also detect it even if it is inside a trailer folder.
