### ISSUE TITLE
Cannot change YouTube link

### ISSUE THREAD

**Issue by JPDVM2014** [nandyalu/trailarr#11]
I have a movie (Halloweentown) where the populated youtube link points to a nonexistent video. This causes an error which stops the whole download task.

I tried changing the YouTube link on the movie's page, but when I hit download it just reverts back to the old link.

 I'm not seeing any permission errors or anything in the logs when I change it. The only error is the one from trying to download the missing video.

**Comment by nandyalu** [comment]
Seems like there is a bug in movie details page. This will be fixed in next release!
