### ISSUE TITLE
Trailarr Downloads trailers for unmonitored and unreleased films

### ISSUE THREAD

**Issue by roofuskit** [nandyalu/trailarr#15]
If I've deleted a movie from something like Emby then Radarr considers the movie un-monitored and I might not go back and clean it up. Because Trailarr downloads trailers for un-monitored movies it's downloading trailers for films I no longer want. A toggle switch to turn this off would be nice.

The major issue with un-released films is that that there is no way for it to know whether a movie has just been announced or is actually in post production with a trailer released. So Trailarr downloads trailers for movies that have not even begun production and they are of course not the correct trailer.

**Comment by nandyalu** [comment]
I understand your concern! What is the actual behavior you are expecting?

**Comment by roofuskit** [comment]
A toggle in settings to stop it from trying to download trailers for un-monitored movies would be nice. And, either prevent it entirely from downloading trailers for un-released films, or at least a toggle in the setting to prevent it. Radarr does track all that, but I'm not sure how easy it is for you to access that through the API. Thank you for listening to my suggestions, and for the work you have already done on this tool. It is great!

**Comment by nandyalu** [comment]
I have been thinking about adding a similar option to wait for movie file to download before downloading the trailer. Do you think that would help with your concerns?

**Comment by roofuskit** [comment]
That sounds like it would solve both issues with one fix.

**Comment by nandyalu** [comment]
Will try and get this added in next release!
