### ISSUE TITLE
home does not display anything and movies only display 30 movies

### ISSUE THREAD

**Issue by elvis0288** [nandyalu/trailarr#16]
so i have 489 movies but when clicking on movies, it will only show 30 movies, is there a reason for this? am i missing some configuration? i was expecting it will show all of those that will not have trailers yet or maybe all of them. maybe a filter option like radarr to filter movies with no trailer yet and movies with trailers

also home will not display anything just a click me button in the middle

Thanks!

**Comment by nandyalu** [comment]
Home: Displays any media for which a Trailer was recently downloaded.
Movies/Series: Displays 30 recently added items.
You can use search for any movies/series.

This needs improvement, but I wasn't sure what to add, so added something basic for time being, to focus on developing the actual logic behind the app. Any suggestions are welcome!

**Comment by elvis0288** [comment]
just something similar to radarr would be nice
![image](https://github.com/user-attachments/assets/2f39c249-1847-4c41-b13c-6f34216d26fe)
![image](https://github.com/user-attachments/assets/9f8780f3-5068-4e28-996f-26aa0429aa9b)
![image](https://github.com/user-attachments/assets/6157e02b-3cc7-4859-9d1c-1c14f8df08f3)
![image](https://github.com/user-attachments/assets/df5fe3bc-6806-40ad-a65f-64267ea5bc86)

**Comment by chasteen432** [comment]
Id say if anything a way to see which trailers have and have not been downloaded.
