### ISSUE TITLE
cannot download trailers.. permission denied

### ISSUE THREAD

**Issue by elvis0288** [nandyalu/trailarr#17]
i have check my permissions on unraid and those folders are set to nobody and read and write for everybody but still i am getting that error.. not sure why.. maybe the fact i am using PUID 1000 and PGID 100 instead of default on radarr is affecting something?

i will add the logs and also my radarr and trailarr config

LOGS:
`2024-08-07T08:59:59-0500 [INFO|main|L085]: Main: Client #505025 connected!

2024-08-07T08:59:59-0500 [INFO|main|L093]: Main: Client #204356 disconnected!

PermissionError: [Errno 13] Permission denied: '/movies'

File "<frozen os>", line 225, in makedirs

File "<frozen os>", line 215, in makedirs

File "<frozen os>", line 215, in makedirs

os.makedirs(trailer_path)

File "/app/backend/core/download/trailer.py", line 137, in download_trailer

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

if download_trailer(media, trailer_folder, is_movie):

File "/app/backend/core/download/trailer.py", line 230, in download_trailers

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

downloaded_media = download_trailers(media_trailer_list, is_movie)

File "/app/backend/core/tasks/download_trailers.py", line 60, in _download_missing_media_trailers

_download_missing_media_trailers(is_movie=True)

File "/app/backend/core/tasks/download_trailers.py", line 84, in download_missing_trailers

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

retval = job.func(*job.args, **job.kwargs)

File "/usr/local/lib/python3.12/site-packages/apscheduler/executors/base.py", line 125, in run_job

Traceback (most recent call last):

2024-08-07T08:59:57-0500 [ERROR|base|L131]: Job "Download Missing Trailers (trigger: interval[1:00:00], next run at: 2024-08-07 09:59:36 CDT)" raised an exception

2024-08-07T08:59:36-0500 [INFO|trailer|L229]: Downloading trailer for '[1]The Lion King'...`

RADARR:
![image](https://github.com/user-attachments/assets/446a5119-19f1-4346-9961-318c7a730f1f)

TRAILARR:
![image](https://github.com/user-attachments/assets/4a4dbcc9-e767-404d-9446-236278850d5d)

**Comment by nandyalu** [comment]
1. Did you enable `Trailer Folder Movie` in settings?
2. Radarr sometimes changes folder permissions on Movie folders. Post the permissions of Movie folder by running `ls -all` in your unraid.
3. Post the permissions of Movie folder by running `ls -all` within Trailarr container.

**Comment by elvis0288** [comment]
1. no, i did not enable trailer folder movie in settings as you suggested me for jellyfin.
2. you might be right.. it is using the 1000 PUID
![image](https://github.com/user-attachments/assets/1505d0cd-2575-4152-ac3f-93b0c74e406b)
3. can i change the appuser for elvis0288 in the trailarr? would that work?
![image](https://github.com/user-attachments/assets/83167e48-67a0-427b-96a4-ab2864babd50)

**Comment by nandyalu** [comment]
Not sure if Unraid supports this at the moment, but there is an option to set custom PUID and PGID for the app. I would suggest you to set them to the same as what you are using for `Radarr` and `Sonarr`

**Comment by nandyalu** [comment]
you can also set APPUSER to desired user.

Environment Variables to set:
```
- APPUSER:appuser #change to desired username you like
- PUID:1000 #default is 1000, change as needed
- PGID:1000 #default is 1000, change as needed
```

**Comment by elvis0288** [comment]
when doing your suggestion, i am getting this

![image](https://github.com/user-attachments/assets/e21201f3-3e53-4923-aa92-c84e88b68134)

**Comment by elvis0288** [comment]
if i use 1000 and 1000 it runs but i still get the error message
![image](https://github.com/user-attachments/assets/6af621de-8af8-43e9-971f-1d8cc058040c)

**Comment by nandyalu** [comment]
there is a bug with current implementation of PUID/PGID and APPUSER. If a user/group with PUID/PGID already exists, it would fail. I am working on a fix.

Also, APPUSER will be removed as it doesn't have any effect inside the container, so will use PUID/PGID instead within the container.

**Comment by elvis0288** [comment]
thank you, so i will remove appuser from the template and leave 1000 and 100 and i guess after your fix 100 should not fail?

thanks!

**Comment by elvis0288** [comment]
after latest update this is the result 
![image](https://github.com/user-attachments/assets/86659420-f473-4b4b-9218-c237e431c52b)
still giving me permission denied even though i am using 1000 and 100 like i do in radarr.. i guess it should be elvis0288 and 1000
![image](https://github.com/user-attachments/assets/e6e3f2c7-7791-4f98-9ac0-2c9b0bf97fe0)

**Comment by nandyalu** [comment]
I removed APPUSER so it always uses the name as appuser but adds it with supplied PUID and checks if group with PGID already exists, if so adds it to that group, otherwise creates new group with PGID

Check your user PUID by running `getent psswd username` and set the PUID with that and PGID to 1000

**Comment by elvis0288** [comment]
so that is what i did on the template
![image](https://github.com/user-attachments/assets/cd669faa-71ff-4fd3-a59c-8020253cb58d)
this is what i got back
elvis0288:x:1000:100:main user:/:/bin/false

but still i got this 
![image](https://github.com/user-attachments/assets/1a090b1c-6ebe-4c89-9f81-ec500824f79f)

and


2024-08-07T18:52:42-0500 [INFO|trailer|L215]: Downloading trailers for 498 movies
2024-08-07T18:52:42-0500 [INFO|trailer|L229]: Downloading trailer for '[1]The Lion King'...
ERROR: Job "Download Missing Trailers (trigger: interval[1:00:00], next run at: 2024-08-07 19:52:42 CDT)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/backend/core/tasks/download_trailers.py", line 84, in download_missing_trailers
    _download_missing_media_trailers(is_movie=True)
  File "/app/backend/core/tasks/download_trailers.py", line 60, in _download_missing_media_trailers
    downloaded_media = download_trailers(media_trailer_list, is_movie)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/backend/core/download/trailer.py", line 230, in download_trailers
    if download_trailer(media, trailer_folder, is_movie):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/backend/core/download/trailer.py", line 137, in download_trailer
    os.makedirs(trailer_path)
  File "<frozen os>", line 215, in makedirs
  File "<frozen os>", line 215, in makedirs
  File "<frozen os>", line 225, in makedirs
PermissionError: [Errno 13] Permission denied: '/movies'
2024-08-07T18:53:02-0500 [ERROR|base|L131]: Job "Download Missing Trailers (trigger: interval[1:00:00], next run at: 2024-08-07 19:52:42 CDT)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/backend/core/tasks/download_trailers.py", line 84, in download_missing_trailers
    _download_missing_media_trailers(is_movie=True)
  File "/app/backend/core/tasks/download_trailers.py", line 60, in _download_missing_media_trailers
    downloaded_media = download_trailers(media_trailer_list, is_movie)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/backend/core/download/trailer.py", line 230, in download_trailers
    if download_trailer(media, trailer_folder, is_movie):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/backend/core/download/trailer.py", line 137, in download_trailer
    os.makedirs(trailer_path)
  File "<frozen os>", line 215, in makedirs
  File "<frozen os>", line 215, in makedirs
  File "<frozen os>", line 225, in makedirs
PermissionError: [Errno 13] Permission denied: '/movies'

**Comment by nandyalu** [comment]
You have a permissions problem. 

Try running this command (probably as sudo):
```bash
cat /etc/passwd
```

PUID and PGID are the numbers in output. Refer [this](https://www.cyberciti.biz/faq/linux-list-users-command/) for help.

Then check the PUID and PGID for the `/movies` and `/tvshows` folders, apply those to Trailarr app.

**Comment by elvis0288** [comment]
well but i do not understand i am using the same PUID and PGID than radarr and sonarr the difference is that when trailarr runs, in the logs it shows that it is actually trying to create a user 'appuser' instead of elvis0288 which is PUID 1000. so at the end the docker folders will have appuser appuser instead of elvis0288 1000


Creating '/data' folder for storing database and other config files
Group with GID '100' already exists, using group 'users'
Creating user 'appuser' with UID '1000'
Changing the owner of app and data directories to 'appuser'
Switching to user 'appuser' and starting the application
Running application as user: appuser

**Comment by morpheus302** [comment]
Same error on unraid here. tried PUID 99 PGID 100 1000/1000 99/100
`cat /etc/passwd`
nobody:x:99:100:nobody:/:/bin/false
`ls -all`
drwxrwxrwx 1 nobody users   62 Aug  7  2021 ./
drwxrwxrwx 1 nobody users   89 Oct  1  2023 ../
drwxrwxrwx 1 nobody users   34 May  1  2022 Docs/
drwxr-xr-x 1 nobody users   29 Sep 10  2022 HB_output/
drwxr-xr-x 1 nobody users 4096 Aug  3 13:37 Movies/
drwxrwxrwx 1 nobody users   76 Aug 29  2021 Music/
drwxr-xr-x 1 nobody users 4096 Jul 21 23:17 Shows/
drwxrwxrwx 1 nobody users   67 Feb  6  2024 books/
drwxrwxrwx 1 nobody users    6 Aug  7  2021 podcasts/

**Comment by nandyalu** [comment]
A quick google search for `unraid docker permissions issue` revealed that there are issues with unraid and docker container permissions.

Looks like a solution is to set PUID to 99 (which is for user nobody) and PGID to 100 (for group users) (taken from this [comment](https://forums.unraid.net/topic/123671-unraid-610-permission-denied-from-docker-containers/?do=findComment&comment=1130646)

@elvis0288 @morpheus302 Can you try using these and report back if it works?

**Comment by nandyalu** [comment]
For the container using 'appdata' user, that is the default, but it's just how containers work. However, the user name and group name doesn't matter, it's the PUID and PGID that matters. And app will set those to the supplied PUID/PGID so it should work. It's working on other systems (I tried on Ubuntu 22.04)

**Comment by elvis0288** [comment]
using 99:100 i get the following on the logs
![image](https://github.com/user-attachments/assets/3147d11f-3c2a-485a-8761-0e04fce214e7)
and it will still failed with the permissions

**Comment by elvis0288** [comment]
i went into sonarr and radarr and use exactly what i have in those which is
![image](https://github.com/user-attachments/assets/96a08c02-585f-477e-a4c3-362c7d009d28)
![image](https://github.com/user-attachments/assets/291d5033-d902-428c-8a43-299b6cdd9de7)
they also have umask but i am not sure if it is needed for trailarr. but that exact same PGID and PUID is what i have on trailarr but it does not work

**Comment by nandyalu** [comment]
I understand that `Radarr` has PGID set to 1000. But can you try setting it as 100 for Trailarr and see if it works?

**Comment by elvis0288** [comment]
i did try 100 as PUID but i am getting the same issue
![image](https://github.com/user-attachments/assets/d149c9c3-0960-4ff1-b987-369959a6c37a)

**Comment by nandyalu** [comment]
still getting permission related errors when trying to download a trailer?

**Comment by elvis0288** [comment]
Yes, still getting permission denied

**Comment by elvis0288** [comment]
something i would like to point out and not sure if it even matter is that inside the movies folder i have 3 other folders 
drwxr-xr-x 1 nobody users 20480 Aug  2 10:53 movies/
drwxr-xr-x 1 nobody users  4096 Aug  6 09:02 movies_animated/
drwxr-xr-x 1 nobody users    10 Jun  5 08:37 movies_requested/

and inside is where the movies from radarr are located

**Comment by nandyalu** [comment]
Here's the code from trailer.py where error occurred:
![image](https://github.com/user-attachments/assets/ae48f0c6-b9e4-4bc1-8ccc-17387c2a8fdd)

Error is occurring on line 137 where it's trying to create the trailer_path (which is the folder path where trailer needs to be saved), here's 2 scenarios where app would try to create that path:
1. line 132 checks if a `Trailers` folder is needed (based on setting `Trailer Folder Movie`) and line 133 will apply it to `trailer_path`. If a `Trailers` folder needs to be created, it will be created in line 137 if it doesn't exist already. At this point trailer_path would look something like `/movies/<movie folder name>/Trailers`
2. If `Trailers` folder is not needed, but movie folder doesn't exist already (line 136), then app would create it in line 137.

So, is it possible that movie folder path doesn't exist yet in your system and when app is trying to create it, it's failing as it doesn't have permissions to create it?

**Comment by elvis0288** [comment]
so checking on the error which is trying to do lion king, it is indeed in there
![image](https://github.com/user-attachments/assets/016f80d1-af6c-4394-9bd2-c9eeaf496292)

**Comment by nandyalu** [comment]
Upon further reading, it looks like template has `Radarr Root` and `Sonarr Root` mapped to `/data/media/movies` and `/data/media/tv` inside the container. But app uses the `/data` folder inside container (which can also be mapped) to save app data and configs. 
![image](https://github.com/user-attachments/assets/f544f938-5c56-44e9-bd79-a95fe0b32bf6)

It is a problem with template itself, in the template `Radarr Root` and `Sonarr Root` should be mapped to `/movies` and `/tv`. As app will get the path for a `The Lion King` movie from Radarr as `/movies/The Lion King (2019)` and when it tries to look for that path inside container, it's not there as it's mapped to `/data/media/movies`

**Comment by elvis0288** [comment]
you were right... so i change the template to this:
![image](https://github.com/user-attachments/assets/c582c5a7-5d13-4779-acc8-94221db60bdb)
looks like it is finally downloading
![image](https://github.com/user-attachments/assets/d9405920-3e19-4331-9c0f-b81d54087826)

**Comment by nandyalu** [comment]
I have no knowledge about unraid templates, can anyone create their own template?

**Comment by elvis0288** [comment]
i will ask JPDVM2014 who created the unraid template to fix it

**Comment by nandyalu** [comment]
@JPDVM2014 looks like you created the Trailarr template for Unraid, can you update it to also take input for both `<LOCAL_MEDIA_FOLDER>` and `<RADARR_ROOT_FOLDER>` and similarly for `Sonarr` too, to make sure both of those gets sent to `docker run` command?

**Comment by JPDVM2014** [comment]
So, I actually made the template based on my working install. I use /data/media/movies and /data/media/tv as my root folders, and it's working fine. 

Maybe it would be better to just leave that blank so people have to fill it in themselves?

![Screenshot_20240808_133032_Vivaldi.jpg](https://github.com/user-attachments/assets/90389658-0041-4ad2-89ef-adc4a5231025)

**Comment by nandyalu** [comment]
Yeah, it would be best to leave them blank to let people fill them in. If you can add a comment or placeholder, that would be great!

Here's the instructions from README, you could add something similar
> Change <LOCAL_APPDATA_FOLDER> to the folder where you want to store the application data.
> Change <LOCAL_MEDIA_FOLDER> to the folder where your media is stored.
> Change <RADARR_ROOT_FOLDERS> to the folder where Radarr stores movies.
> Change <SONARR_ROOT_FOLDERS> to the folder where Sonarr stores TV shows.

**Comment by JPDVM2014** [comment]
Actually you are right, I can just put the LOCAL_MEDIA_FOLDER like you have. Then it will have to be filled out manually before it will work at all.

I also added the PUID and PGID variables so they are there if anyone needs to adjust them.

![Screenshot_20240808_134904_Vivaldi.jpg](https://github.com/user-attachments/assets/46b99ee1-841d-419b-96b2-05bcbadc77a8)

**Comment by nandyalu** [comment]
Perfect! Thank you :)

**Comment by PRO50347** [comment]
i am getting the same error and i have switched it all to /movies and /tv 
my movies are download and moving over. but tv shows I get [ERROR|trailer|L267]: TrailersDownloader: Failed to download trailer for '[1599]Community': Failed to move trailer to folder: [Errno 13] Permission denied: '/Media'
can anyone help please .

**Comment by nandyalu** [comment]
@PRO50347 there might be a problem with your config. The error clearly says that permission denied while moving trailer to your media folder. Can you share your config?

**Comment by PRO50347** [comment]
![Image](https://github.com/user-attachments/assets/03c4ba01-6ac0-4505-a2c0-f3f662529447)

![Image](https://github.com/user-attachments/assets/987bbefe-f41d-44d7-8358-1fe8fa8e1ce4)

![Image](https://github.com/user-attachments/assets/f8ca001e-cb6a-400b-8198-106254036e03)

**Comment by PRO50347** [comment]
let me kno if there is more that u need
