### ISSUE TITLE
get the auto translate option from youtube if no CC are found

### ISSUE THREAD

**Issue by elvis0288** [nandyalu/trailarr#19]
**Is your feature request related to a problem? Please describe.**
so my wife does not know english and watching the trailers with spanish subtitles is totally a plus

**Describe the solution you'd like**
on youtube, you can now select a subtitle from the options but you can also do auto translate and choose language you want to translate to and youtube will probably try its best to translate to that language

**Describe alternatives you've considered**
no solution, i guess just watching it on english without subtitles is the only other option

**Additional context**
this is the option i am talking about and comparing and listening it actually makes a good job so not sure if this is something that it is even possible to do
![image](https://github.com/user-attachments/assets/929d16ac-364e-4354-a195-e1c9fbedd389)

**Comment by nandyalu** [comment]
App uses [yt-dlp](https://github.com/yt-dlp/yt-dlp) to download videos from YouTube. There doesn't seem to be an option for that right now! It does try and download the auto-generated subtitles if they are available.
