### ISSUE TITLE
[Request] Customizable file names

### ISSUE THREAD

**Issue by StayFlyEatFries** [nandyalu/trailarr#27]
Currently, all trailers are saved as "[movie name] - Trailer-trailer.extension".

I would love a setting that allowed users to modify this string.

Thank you in advance.

**Comment by nandyalu** [comment]
Will try and add this during Frontend revamp

**Comment by nandyalu** [comment]
Will `media title` `year` options be enough to customize file names?

**Comment by StayFlyEatFries** [comment]
> Will `media title` and `year` options be enough to add to customizable file names?

Yes, that's more than enough for me, personally. There's a good chance I would just set it to something universal, like "Official Trailer", instead of including any text pulled from the movie metadata. But having those options would be nice too.

**Comment by nandyalu** [comment]
Added this in comit 5d9e7a1735c1aadfe26ebef603fb66c65a3ab0e4, also added options for `resolution`, `vcodec` and `acodec` in commit b450b572c000e92da41e81dd0a497b26f796a469. This will be included in next release!
