### ISSUE TITLE
[Request] WebGUI Authentication

### ISSUE THREAD

**Issue by anthony0030** [nandyalu/trailarr#31]
It would be great to be able to set a username and password to access the interface, to keep the APIkeys safe.

**Comment by nandyalu** [comment]
This can be added!

**Comment by nandyalu** [comment]
Commit 1963a314b091c050e38d383d16dde7ecb3afa92f fixes this! Will be included in next release

**Comment by jimmayx** [comment]
Hey, to save some pain (I've just spent an hour trying to figure out whether there was a secret login I had set during deployment), can you include the default credentials in your docs? This was really painful to find and less skilled users would have given up.

**Comment by nandyalu** [comment]
@jimmayx Appreciate the suggestion. I wanted to add this somewhere in the docs, but didn't know where!

I just added it to Docs here: https://nandyalu.github.io/trailarr/setup/connections/#add-radarrsonarr-connections

If you have any suggestions, please let me know.

P.S: You would have found it on github release notes and issue comments.

**Comment by geebru** [comment]
Sorry to necro this again - but is there a way to edit what the default login credentials are? I'm not finding anything in the app or env setup.

**Comment by nandyalu** [comment]
Unfortunately there is no option to do that right now, I did add this as an option via an Environment variable `WEBUI_PASSWORD` that will be available in the next release!
