### ISSUE TITLE
Connections missing after restart

### ISSUE THREAD

**Issue by saulo-m** [nandyalu/trailarr#4]
Hi there!

I'm encountering an issue when running the application in Docker.

**Problem Description:**
After adding Radarr and Sonarr, even after downloading subtitles, if I shut down the Docker container using `docker-compose down`, the connections disappear. Upon restarting, I receive errors indicating a missing database and missing connections.

**Steps to Reproduce:**
1. Add Radarr and Sonarr to the application.
2. Download subtitles.
3. Shut down the Docker container with `docker-compose down`.
4. Restart the container.

**Expected Behavior:**
The connections and database should persist after shutting down and restarting the Docker container.

**Actual Behavior:**
After restarting the Docker container, the connections vanish, and I receive errors about a missing database and missing connections.

Any assistance would be greatly appreciated!

Thank you.

[error.log](https://github.com/user-attachments/files/16475192/error.log)

**Comment by nandyalu** [comment]
App saves database and other app data in /data folder. 
Did you add a volume mount for `/data` folder?

**Comment by saulo-m** [comment]
Hi there! I got it working!

It was missing a "/" in the DATABASE_URL in .env file. The correct address is "DATABASE_URL='sqlite:////data//trailarr.db'".

Also, if the debug flag is True, the app wont work. It think this may be caused by this line: https://github.com/nandyalu/trailarr/blob/b6a72c2bcbcb7b60764f9eef62484e169172a4a9/backend/core/base/database/utils/engine.py#L12C44-L12C51

**Comment by saulo-m** [comment]
Another thing I noted: 

When performing an "Arr Data Refresh" with a connection down or when Radarr/Sonarr are yet starting, the movies and TV shows data in the Trilarr database is lost. This results in empty "movies" and "series" tables after the refresh.

## Steps to Reproduce

1. Start only the Trilarr Docker container with populated 'movies' and 'series' tables.
2. Perform an "Arr Data Refresh" under one of these conditions:
   a. Connection to Radarr/Sonarr is down
   b. Radarr/Sonarr services are slow to start

## Expected Behavior

The Trilarr database should retain the existing data in the "movies" and "series" tables even when a refresh fails due to connection issues.

## Actual Behavior

After the refresh attempt, the "movies" and "series" tables in the Trilarr database become empty, losing all previously stored data.

**Comment by nandyalu** [comment]
Glad you got it working! 

> It was missing a "/" in the DATABASE_URL in .env file. The correct address is "DATABASE_URL='sqlite:////data//trailarr.db'".

`DATABASE_URL` defaults to "sqlite:////data/trailarr.db", not sure why you would need "//" between `data` and `trailarr.db`. Did you overwrite that in Docker Compose?

> Also, if the debug flag is True, the app wont work. It think this may be caused by this line: https://github.com/nandyalu/trailarr/blob/b6a72c2bcbcb7b60764f9eef62484e169172a4a9/backend/core/base/database/utils/engine.py#L12C44-L12C51

I added that intentionally to help with running tests, however, I will change that and maybe add another variable specific to testing!

**Comment by nandyalu** [comment]
> Another thing I noted:
> 
> When performing an "Arr Data Refresh" with a connection down or when Radarr/Sonarr are yet starting, the movies and TV shows data in the Trilarr database is lost. This results in empty "movies" and "series" tables after the refresh.
> 
> ## Steps to Reproduce
> 1. Start only the Trilarr Docker container with populated 'movies' and 'series' tables.
> 2. Perform an "Arr Data Refresh" under one of these conditions:
>    a. Connection to Radarr/Sonarr is down
>    b. Radarr/Sonarr services are slow to start
> 
> ## Expected Behavior
> The Trilarr database should retain the existing data in the "movies" and "series" tables even when a refresh fails due to connection issues.
> 
> ## Actual Behavior
> After the refresh attempt, the "movies" and "series" tables in the Trilarr database become empty, losing all previously stored data.

#5 opened for this

**Comment by saulo-m** [comment]
> `DATABASE_URL` defaults to "sqlite:////data/trailarr.db", not sure why you would need "//" between `data` and `trailarr.db`. Did you overwrite that in Docker Compose?

I have edited the DATABASE_URL directly in .env file at /data. My docker-compose file is:

```
  trailarr:
    image: nandyalu/trailarr:latest
    container_name: trailarr
    environment:
      - TZ=UTC
    ports:
      - 7889:7889
    volumes:
      - "${CONFIG}/config/trailarr:/data"
      - "${STORAGE}/Movies:/Movies"
      - "${STORAGE}/Tvshows:/Tvshows"
    restart: unless-stopped
```

**Comment by nandyalu** [comment]
Is `trailarr.db` located in `/data` directory?

Can you log into container and post the contents of `/data` directory?

**Comment by saulo-m** [comment]
Is, its there.

```
# cd /data && ls
logs  trailarr.db  trailarr.db.old  web
```
