### ISSUE TITLE
[Request] Audio volume level setting

### ISSUE THREAD

**Issue by DenisSolonevich** [nandyalu/trailarr#41]
It would be nice to have an option to change the audio volume level of the trailer.
In my case on the 5.1 system 2.0 content sometimes sounds way too loud.

In the local build I use the next quickfix to decrease sound level two times.
```
# Set audio specific options
    audio_format = _AUDIO_CODECS[app_settings.trailer_audio_format]
    output_options.append("-af \"volume=0.5\"")
    output_options.append("-c:a")
```

I see this feature as a slider (e.g. 0% to 200%) in the settings with description that "it will be applied to the new trailers only".

**Comment by nandyalu** [comment]
This can definitely be added as an advanced option. Do you think it would be useful to make this generic like `FFMPEG audio options" and "FFMPEG Video options" so that if anyone wants to modify the default options, they will have the option to do so?

**Comment by DenisSolonevich** [comment]
It is hard to say whether all options of FFMPEG audio/video needed right now. Maybe :-). You already let users specify protocols, looks like good enough + volume level. Maybe I would also let user choose audio max bitrate that YouTube provide but I'm not an expert here and don't know whether 128kb is good enough or YouTube can provide something better. 

In my family there are a few use-cases right now:
1) "Cinema mode" - big screen projector; living room; Emby; movie/tv episodes. I configured Emby to show a few trailers ahead of every movie. So in this moment as part of preparation the audio volume already setup to the high level. And quality of trailers are really important because of big screen and sound system. For this use case I would prepare trailers in max quality that YouTube can provide.
2) "Web mode" - mobile or laptop; sometimes on the way; Emby; play on background while doing something. In this case quality of trailers absolutely not important because of smaller screens, less speakers, surround noise.

The first use-case has higher priority for me so I'd like to have an option to get the best quality, just with a way to change a bit volume level :-)
