### ISSUE TITLE
[Request] Allow me to configure scheduled task intervals

### ISSUE THREAD

**Issue by rpschube** [nandyalu/trailarr#43]
**Is your feature request related to a problem? Please describe.**
The "Download Missing Trailers" runs every hour, briefly taking up 30% of my CPU. Not a huge deal, but I don't need this happening every hour.

**Describe the solution you'd like**
I would like to be able to set a minutes or hours value for the interval at which all of the scheduled tasks run. This would work similarly to the existing monitor interval setting:

![image](https://github.com/user-attachments/assets/08fefe6f-0843-467e-bc47-0cb116f5e5a7)

**Describe alternatives you've considered**
Keeping the container shut down and only starting it up it once a day for a single run of all it's scheduled tasks.

**Additional context**
Everything else works great!

**Comment by nandyalu** [comment]
> I would like to be able to set a minutes or hours value for the interval at which all of the scheduled tasks run. This would work similarly to the existing monitor interval setting

That is exactly how it works right now! App uses the same interval set in `Monitor Interval` for all tasks except for `Image Refresh` which runs every 6 hours.

**Comment by rpschube** [comment]
Hmm, I suppose then it's not working for me. I have the Monitor Interval setting set to 480 as you can see above. However the tasks seem to be running at their same default schedules.

![image](https://github.com/user-attachments/assets/b6010fb4-6b1c-4727-90b1-6e639bd3e850)

**Comment by nandyalu** [comment]
Tasks are scheduled when app starts, changing them won't be applied immediately. A restart is needed to set new scheduled tasks with updated intervals.

That tells me, I need to add this to docs, and maybe show a warning or something that container restart is needed to take effect. Thanks for bringing it up!
