### ISSUE TITLE
[Bug] Text Fields acting strange

### ISSUE THREAD

**Issue by Jdiesel87** [nandyalu/trailarr#44]
Not really sure how to describe this but some of the text fields are not working correctly.

In the main Search field the "F" key isn't registering

In the Setting Cookies location field I want to type "/config/cookies.txt" but only "/con" gets accepted. Pasting into the field works.

**Comment by nandyalu** [comment]
App is listening for "F" key press to start searching, this could be interfering with typing in text fields. I will try and apply a fix.
