### ISSUE TITLE
Media gets deleted in database if Radarr/Sonarr connections are down

### ISSUE THREAD

**Issue by nandyalu** [nandyalu/trailarr#5]
When performing an "Arr Data Refresh" with a connection down or when Radarr/Sonarr are yet starting, the movies and TV shows data in the Trailarr database is lost. This results in empty "movies" and "series" tables after the refresh.

## Steps to Reproduce

1. Start only the Trailarr Docker container with populated 'movies' and 'series' tables.
2. Perform an "Arr Data Refresh" under one of these conditions:
   a. Connection to Radarr/Sonarr is down
   b. Radarr/Sonarr services are slow to start

## Expected Behavior

The Trailarr database should retain the existing data in the "movies" and "series" tables even when a refresh fails due to connection issues.

## Actual Behavior

After the refresh attempt, the "movies" and "series" tables in the Trailarr database become empty, losing all previously stored data.

_Originally posted by @saulo-m in https://github.com/nandyalu/trailarr/issues/4#issuecomment-2269756076_

**Comment by nandyalu** [comment]
@saulo-m I know what's happening here, during "Arr Data Refresh", app will track for any movies/series that did not exist in Radarr/Sonarr and deletes them from database. This will ensure that any media deleted from Radarr/Sonarr will be deleted from Trailarr as well.

I will see how to avoid deleting media when connection fails

**Comment by nandyalu** [comment]
v0.0.4-beta release fixes this!

**Comment by saulo-m** [comment]
It's fixed!

I did a refresh with the arr services down and it didn't vanish the data.

 Thank you! 

```
trailarr        | ERROR: ConnectionManager: Failed to get media data from Arr application.
trailarr        | 2024-08-05T17:58:52-0300 [ERROR|connection_manager|L074]: ConnectionManager: Failed to get media data from Arr application.
trailarr        | WARNING: ConnectionManager: No media found in the Arr application
```
