### ISSUE TITLE
[Bug] Error: 400 'PathMappingCRU' object has no attribute '_sa_instance_state' when using Path mappings

### ISSUE THREAD

**Issue by alexkahler** [nandyalu/trailarr#53]
**Describe the bug**
When adding a new connection in Sonarr, and specifying path mappings (i.e., /share/Multimedia/TV Shows/ to /share/Multimedia/Trailers) and then trying to submit, Trailarr says, "Error: 400 'PathMappingCRU' object has no attribute '_sa_instance_state'"

Docker volume mappings for Sonarr:
volumes:
 - /share/Docker/sonarr:/config
 - /share:/share

Docker volume mappings for Trailarr:
volumes:
 - /share/Docker/trailarr/config:/config
 - /share:/share

Sonarr and Radarr have the same setup in terms of volume mappings. Only difference is that Sonarr has multiple root folders (Anime and TV Shows).

**Steps To Reproduce**
1. Click add new connection
2. Fill out Sonarr connection details
3. Add path mappings
4. Click submit

**Screenshots**
![image](https://github.com/user-attachments/assets/832e4eee-f58b-480a-92ae-6f6e283d4995)

Above mentioned mapping worked in Radarr:
![image](https://github.com/user-attachments/assets/d601bea8-0ae4-46e3-ae5b-94894dfb5007)

**App Information (please complete the following information):**
 - Base OS: Docker
- Architecture: arm64
 - Version v0.2.0-beta

**Additional context**

**Comment by nandyalu** [comment]
Can you provide some logs as well?

**Comment by Jamisonfitz** [comment]
I experienced this as well, it does allow you to save the connection without mappings without error and then will let you add the mappings after.

**Comment by alexkahler** [comment]
> I experienced this as well, it does allow you to save the connection without mappings without error and then will let you add the mappings after.

Thanks, that worked for me.

**Comment by nandyalu** [comment]
Found a bug in code when creating a `Connection` with `PathMappings`.
