### ISSUE TITLE
[Bug]  Invalid data found when processing input

### ISSUE THREAD

**Issue by Hello-World-Traveler** [nandyalu/trailarr#60]
All trailers the script has downloaded has a file size of 0b, A lot of empty files now.

```
ERROR: VideoAnalysis: Error: [mov,mp4,m4a,3gp,3g2,mj2 @ 0x558240063280] moov atom not found
 Invalid data found when processing input
```
```
[INFO|video|L042]: TrailersDownloader: 'Trailers': [Merger] Converting downloaded file...
[INFO|video|L042]: TrailersDownloader: 'Trailers': [EmbedSubtitle] Converting downloaded file...
[INFO|video|L042]: TrailersDownloader: 'Trailers': [EmbedSubtitle] Converting downloaded file...
[INFO|video|L042]: TrailersDownloader: 'Trailers': [ModifyChapters] Converting downloaded file...
[INFO|video|L042]: TrailersDownloader: 'Trailers': [ModifyChapters] Converting downloaded file...
[INFO|video|L042]: TrailersDownloader: 'Trailers': [CopyStream] Converting downloaded file...
 [INFO|video|L042]: TrailersDownloader: 'Trailers': [CopyStream] Converting downloaded file...
```
The settings are mp4 h.264 aac (converting from vp9)
https://github.com/nandyalu/trailarr/issues/59

**Comment by nandyalu** [comment]
Not sure what is happening here, but are you still seeing this issue?

**Comment by Hello-World-Traveler** [comment]
Since it's downloading inside docker, I am not able to see the file as easily in the OS file system. I haven't upgraded yet to the new beta.

**Comment by nandyalu** [comment]
Downloaded trailer will be moved to your media folder, you can see it there

**Comment by Hello-World-Traveler** [comment]
After it is done. the file is 0 mb. Sometime today I will install the latest update and try again.

**Comment by Hello-World-Traveler** [comment]
I've notice that there is something wrong with the naming, for me its showing v0.2.1-beta not v0.2.2-beta. 

Default settings for video worked how it should, I will let it use AV1 and opus 

Trailer Resolution
Resolution of the trailer video file.
Valid values: 240, 360, 480, 720, 1080, 1440, 2160
This should be a selectable option to make it easier..

**Comment by nandyalu** [comment]
v0.2.2-beta is the latest release. Make sure your docker compose has image as `nandyalu/trailarr:latest`

> Trailer Resolution
Resolution of the trailer video file.
Valid values: 240, 360, 480, 720, 1080, 1440, 2160
This should be a selectable option to make it easier..

It can be updated to a dropdown, I just didn't want to spend much time on implementing a dropdown at the time. However, when you input a value, it will find it's nearest resolution and set to that. Try setting that value to 1000 and once you save it, backend will update it to 1080. Not very intuitive, but it works!

**Comment by Hello-World-Traveler** [comment]
>v0.2.2-beta is the latest release. Make sure your docker compose has image as nandyalu/trailarr:latest

nandyalu/trailarr:0.2.2-beta nandyalu/trailarr:latest	701.6 MB 2024-10-22 08:43:11. Not sure why after pulling it again and again., its still 0.2.1.  Removed image and pulled nandyalu/trailarr:latest but it still shows up as org.opencontainers.image.version 	0.2.1-beta

**Comment by nandyalu** [comment]
What does it show under `Settings > About`?

**Comment by Hello-World-Traveler** [comment]
v0.2.1-beta Latest. Doesn't matter if I pull the latest.

**Comment by nandyalu** [comment]
Are you still seeing this issue?

**Comment by Hello-World-Traveler** [comment]
`[ERROR|docker_check|L091]: UpdateChecker: Error: Could not update details from Docker Hub.`

Could this be why it still shows v.2.1-beta?
