### ISSUE TITLE
sign in to confirm information

### ISSUE THREAD

**Issue by shedman214** [nandyalu/trailarr#62]
i'm getting this error when i'm running the task "scan for missing trailers"

`yt_dlp.utils.DownloadError: ERROR: [youtube] pLWda_RrQn4: Sign in to confirm your age. This video may be inappropriate for some users.`

**Comment by nandyalu** [comment]
You get this error when you downloading an age restricted video from YouTube!

Supplying a YouTube cookie file in Advanced Settings will solve this!

**Comment by shedman214** [comment]
> You get this error when you downloading an age restricted video from YouTube!
> 
> Supplying a YouTube cookie file in Advanced Settings will solve this!

@nandyalu where do I get the cookie file?
