### ISSUE TITLE
[Request] Add option to disable password authentication

### ISSUE THREAD

**Issue by CygnusHyoga** [nandyalu/trailarr#67]
**Is your feature request related to a problem? Please describe.**

When using trailarr with SSO like Authentik, Authuelia, etc. with Forward auth for example with traefik, you will have double auth: one in SSO and another in trailarr location auth, because is enable by default.

**Describe the solution you'd like**

Add an environment variable to disable password authentication.

**Describe alternatives you've considered**

- Add an option inside the GUI  to disable password authentication.
- Add OIDC auth integration.

**Additional context**
None.

**Comment by nandyalu** [comment]
I will try to add disabling authentication as an option by setting an environment variable.
