### ISSUE TITLE
[Request] Add Kubernetes probes (liveness and readiness)

### ISSUE THREAD

**Issue by CygnusHyoga** [nandyalu/trailarr#68]
**Is your feature request related to a problem? Please describe.**

When using trailarr with kubernetes, it is currently not possible to add liveness or readiness probes to the root url or another url, as it gives a 401 error.

**Describe the solution you'd like**

It would be good to add two endpoints, for example:

- /readiness
- /liveness

Which can return the status 200 OK without authentication.

**Describe alternatives you've considered**

Add only one endpoint for example /status which can return the status 200 OK without authentication.

**Additional context**

FastAPI liveness and readiness probes example:

[Deploying a lightning-fast FastAPI Python REST-API with Docker and Kubernetes: A step-by-step guide for scalable and reliable application](https://kndoni.medium.com/deploying-a-lightning-fast-fastapi-python-rest-api-with-docker-and-kubernetes-a-step-by-step-guide-acf14ea57a99)

**Comment by nandyalu** [comment]
My mistake! It's just `/status` and not `/api/v1/status`

**Comment by CygnusHyoga** [comment]
It's working with `/status` Thanks!!
