### ISSUE TITLE
[Request] Add support for multiple Trailers and Extras

### ISSUE THREAD

**Issue by CygnusHyoga** [nandyalu/trailarr#69]
**Is your feature request related to a problem? Please describe.**

It would be great to support downloading multiple trailers and extras for Movies and Series like [TMDB](https://www.themoviedb.org) offers, for example: 

- Teasers
- Clips
- Behind the Scenes
- Bloopers
- Featurettes
- Opening Credits

**Describe the solution you'd like**

Download the multiple trailers and/or extras for use in popular applications (Plex/Kodi/Emby/Jellyfin)

**Describe alternatives you've considered**

N/A

**Additional context**

Example with arr-scripts:

- [arr-scripts](https://github.com/RandomNinjaAtk/arr-scripts)

**Comment by nandyalu** [comment]
You can download another trailer for a movie/series by opening it in web app, updating the youtube trailer id and clicking on download. App cannot do that automatically though.

Downloading extras is not in scope of Trailarr at the moment. Maybe in the future once app becomes stable.
