### ISSUE TITLE
[Bug] Known working cookies not working in trailarr

### ISSUE THREAD

**Issue by Glynax** [nandyalu/trailarr#70]
**Describe the bug**
I have 3 ytdl-sub containers (ytdlp) that all use my google accounts youtube cookie and they seem to bypass age restriction and everything else, but in trailarr I can't download ANYTHING because of this "yt_dlp.utils.DownloadError: ERROR: [youtube] YwEZv8NJSEA: Sign in to confirm your age. This video may be inappropriate for some users."
The path in trailarr and permissions are correct and I'm not sure what else there is for me to check really.

I've even followed instructions on your subreddit and documentation here, trying to make another youtube/google account and doing all the directions to a T and I still get the same error.

The only thing different between my compose and yours I think is I am running mine inside a gluetun docker network so I don't get IP banned from youtube again.

**Steps To Reproduce**

**Actual behavior**
A clear and concise description of what is happening.

**Expected behavior**

**Screenshots**
![image](https://github.com/user-attachments/assets/8865dea8-0a1e-4dd6-8cdb-e032953851cd)
![image](https://github.com/user-attachments/assets/9ee70dca-87ea-48c5-9c9b-7872f68798e1)

**App Information (please complete the following information):**
 - Base OS: [e.g. Ubuntu] proxmox
- Architecture: (run `dpkg --print-architecture` to find out). [e.g. arm64, amd64] amd64
 - Version [e.g. 22.04] 6.8.12-4-pve
 - Browser (if related to webpage) [e.g. chrome 127.0.6533.89 (Official Build) (64-bit)]

**Additional context**

`  trailarr:
        image: nandyalu/trailarr:latest
        container_name: trailarr
        network_mode: "service:gluetun"
        environment:
            - TZ=America/Detroit
            - PUID=1000
            - PGID=1000
       # ports:
       #     - 7889:7889
        volumes:
            - /mnt/TempZoom/opt/trailarr/config:/config
            - /mnt:/mnt
     #       - <LOCAL_MEDIA_FOLDER>:<SONARR_ROOT_FOLDER>
        restart: unless-stopped

`

**Comment by DenisSolonevich** [comment]
> Do you mind if I ask what are those other yt-dl containers? I am only asking because I want to check their implementation of yt-dl

I think I also faced this issue sometimes. I added some local logging to check that cookies path read correctly - it is. On the code level for the first sight it looked ok so I didn't dig deeper.
If I remember correctly I compered it with a TubeArchivist.

**Comment by Glynax** [comment]
ytdl-sub, it's kind of just a fancy wrapper around dlp.

https://ytdl-sub.readthedocs.io/en/latest/introduction.html

**Comment by nandyalu** [comment]
Can you check the cookies file and confirm that it starts with the below 2 lines?

![Screenshot_20241201_234345_RaspController.jpg](https://github.com/user-attachments/assets/9b36c422-4be8-4fc9-8297-ce6c63e49979)

**Comment by Glynax** [comment]
Yep

![image](https://github.com/user-attachments/assets/087aad9d-a77f-4124-805e-9b88964e2348)

**Comment by nandyalu** [comment]
That confirms that yt-dlp used that cookies. 

I am using cookies exported from an incognito tab as described [here](https://github.com/yt-dlp/yt-dlp/wiki/Extractors#logging-in-with-oauth)

Moreover, there seems be multiple issues with yt-dlp and YouTube cookies [yt-dlp issue](https://github.com/yt-dlp/yt-dlp/issues/8227)

Sadly, there is not much I can do!

**Comment by Glynax** [comment]
Ah that sucks I didn't realize they were having issues. 
I guess all I can ask of you is instead of the entire task breaking when a video fails (for say being age limited and not having a cookie) can it continue so I can at least use your software? Or make that an option to toggle? I'm sure if that were the case I could get a large % of my trailers downloaded instead of almost none.

**Comment by nandyalu** [comment]
I can definitely do that!

**Comment by nandyalu** [comment]
@Glynax is Trailarr able to download the trailers without failing after the latest update?

**Comment by Glynax** [comment]
Yep it's perfect now thank you so much! I don't know if this is possible but could you add a counter that gives the number of trailers downloaded total for shows and movies? And also a total space taken up by them, I love stats like that.

**Comment by nandyalu** [comment]
There are some numbers displayed in Settings > About.

Are you looking for something else?

**Comment by Glynax** [comment]
Oh I totally missed those. So what I'm looking for is a breakdown of how many trailers were for series and how many were for movies overall, I see the total for both combined I assume but not individually. And the other thing is I'm curious how much space the trailers all collectively take, I'm not going to delete them I just like the stats. 
Another question I just noticed off of this, each run of the download trailer task ends after about 5 minutes because I believe it's going through the entire list and just hitting things that are age restricted but as you can see there should still be pleeeenty more trailers to download so I'm curious what I'd need to find to look into that.
![image](https://github.com/user-attachments/assets/b5a23b82-de60-498b-93e0-9d703a37e2b6)
