### ISSUE TITLE
[Bug] Movie title consisting of numbers does not show up in search results

### ISSUE THREAD

**Issue by alphadijkstra** [nandyalu/trailarr#86]
**Describe the bug**
When searching for a full movie title consisting of only numbers, the movie cannot be found in the search bar.
However, when searching for it partially. Like "191" does return a result.

**Steps To Reproduce**
1. Have a movie with only numbers in your library, like "1917"
2. Search for the movie in the movies tab of Trailarr
3. Notice it cannot find it.

**Comment by nandyalu** [comment]
That's intended behavior! App tries to parse any 4 numbers typed together as year to find movies from that year only.

For example, if you search for "a 2024" you will only get movies that has letter a in their title and from year 2024.

The alternate is to remove the year filter or create some complex methods that breaks on other things and more importantly slower search results. 

There's only a handful of movies that has 4 digits in their titles so I thought it's okay to compromise on that

**Comment by alphadijkstra** [comment]
That is fair. I did not know this. Thanks for the explanation! I will close it now.
