### ISSUE TITLE
[Request]

### ISSUE THREAD

**Issue by mwarner416** [nandyalu/trailarr#90]
**Is your feature request related to a problem? Please describe.**
I've discovered that when a movie has been added to Radarr, but hasn't been released yet.  Trailarr will go out and snag the trailer, then create the folder and add it to respective location.

**Describe the solution you'd like**
I would recommend checking to see if the media has been downloaded, before proceeding with downloading the trailer.

**Comment by nandyalu** [comment]
There is an option in Settings for that `Wait for Media`!
